export const HOME_URL = '/'
export const LOGIN_URL = '/login'
export const REGISTER_URL = '/register'
export const UPCOMING_URL = '/upcoming'
export const SEARCH_URL = '/search'
export const DETAIL_URL = '/movies/:movieId'